### ISSUE TITLE
Cursor not showing on TextFields

### ISSUE THREAD

**Issue by aaronksaunders** [aaronksaunders/AlloyAppTemplate#1]
@ricardoalcocer do you have any guesses to why I cannot get the cursor to show properly in my Android app on the text fields? I have followed instructions from documentation and repeated what works in other apps, but it is not working with this template.

Was wondering if it has to do with the `builtin_themes.xml` or the use of the actionbar plugin

**Comment by ricardoalcocer** [comment]
This is what I do in builtin_themes.xml to get the cursor to show:

```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">

  <!-- Cursor in text field -->
  <style name="Theme.Mdnote" parent="Theme.AppCompat">
    <item name="android:editTextStyle">@style/editText</item>
  </style>

  <style name="editText" parent="@android:style/Widget.Holo.Light.EditText">
    <item name="android:textCursorDrawable">@null</item>
    <item name="android:textColorHint">@color/cursor</item>
  </style>
  <!-- ### -->
</resources>
```

I got this pretty much straight from : https://developer.appcelerator.com/question/164315/cursor-color-in-a-textbox

**Comment by ricardoalcocer** [comment]
Notice **Theme.Mdnote**, that's the theme name I use in the manifest

```
<manifest>
            <application android:theme="@style/Theme.Mdnote"/>
</manifest>
```

**Comment by aaronksaunders** [comment]
So I shouldn't need to create another resource file, just update the
builtin_themes file; will give that a try.

BTW will be using this in my class and will give you a shout out for the
work!

On Saturday, February 7, 2015, Ricardo Alcocer notifications@github.com
wrote:

> This is what I do in builtin_themes.xml to get the cursor to show:
> 
> <?xml version="1.0" encoding="utf-8"?>
> <resources xmlns:android="http://schemas.android.com/apk/res/android">
> 
>   
>   <style name="Theme.Mdnote" parent="Theme.AppCompat">
>     <item name="android:editTextStyle">@style/editText</item>
>   </style>
> 
>   <style name="editText" parent="@android:style/Widget.Holo.Light.EditText">
>     <item name="android:textCursorDrawable">@null</item>
>     <item name="android:textColorHint">@color/cursor</item>
>   </style>
>   
> </resources>
> 
> I got this pretty much straight from :
> https://developer.appcelerator.com/question/164315/cursor-color-in-a-textbox
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aaronksaunders/AlloyAppTemplate/issues/1#issuecomment-73386440
> .

## 

## -- http://www.clearlyinnovative.com/build-it/

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
201.214.5926  (M)
blog@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by ricardoalcocer** [comment]
Awesome!  Let me know if it works for you.

**Comment by aaronksaunders** [comment]
@ricardoalcocer didn't work at all, could not get the second window to use the new theme, ended up specifying the theme directly on the window. I copied the code you provided into your template app and it works fine on the first page, but on the new page, which I believe is a new Activity, the theme appears to get lost.

**Comment by ricardoalcocer** [comment]
Hmm...so now that I check, it's not working for me either, in the project it was support to be working on.  Let me ask around..really odd.

**Comment by aaronksaunders** [comment]
@ricardoalcocer i believe it might be because of the way the windows are Activities now? Not sure because I am more of an IOS than Android guy. You can see my solution here [https://github.com/aaronksaunders/AppC-Alloy-Book-Misc-Ch3/blob/master/app/styles/createItem.tss#L3](https://github.com/aaronksaunders/AppC-Alloy-Book-Misc-Ch3/blob/master/app/styles/createItem.tss#L3)

**Comment by ricardoalcocer** [comment]
I have no problem getting my ActionBarStyle transferred to other windows though...what I'm not getting is the cursor, which I used to...
